name: ohif/deploy-v3-upstream-with-add-ons

on:
  workflow_dispatch:

jobs:
  link_build_and_deploy:
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      
      - name: Clone and install OHIF dependencies
        run: |
          git clone https://github.com/OHIF/Viewers.git
          cd Viewers
          git checkout v3.9.3
          yarn install --frozen-lockfile

      - name: Clone and install ohif-secondary-dicomweb-extension dependencies
        run: |
          git clone https://github.com/fedorov/ohif-secondary-dicomweb-extension.git
          cd ohif-secondary-dicomweb-extension
          yarn install --frozen-lockfile

      - name: Link ohif-secondary-dicomweb-extension to OHIF and build
        run: |
          cd Viewers
          wget -O ./firebase.json "${{ vars.OHIF_FIREBASE_JSON_URL }}"
          wget -O ./platform/app/public/config/test.js "${{ vars.OHIF_CONFIG_JS_URL }}"
          yarn cli link-extension ../ohif-secondary-dicomweb-extension
          PUBLIC_URL=/ APP_CONFIG=config/test.js yarn build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0.7.1
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 5d
          projectId: "${{ vars.FIREBASE_PROJECT_ID }}"
          entryPoint: ./Viewers
          channelId: live 
          # channelId: # 'pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}'
